# Generated by Django 4.0.3 on 2022-04-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_remove_create_team_create_team_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acntspayslip',
            name='acntspayslip_delay',
        ),
        migrations.RemoveField(
            model_name='acntspayslip',
            name='acntspayslip_deltype',
        ),
    ]
